### ISSUE TITLE
Alternative way: remove POPCNT check from rl_x64_f.dll

### ISSUE THREAD

**Issue by beatcracker** [ogurets/popcnt_emulator#2]
Just found your repo, awesome job! 

I've been trying to fix this issue myself and found that `NOP`ing  POPCNT check in `rl_x64_f.dll` works. It really looks like the codepaths with POPCNT are not used at all.

Here is [my solution](https://pcgamingwiki.com/wiki/Quantum_Break#POPCNT_instruction) if anybody interested:

- Get hex editor. [HxD](https://mh-nexus.de/en/hxd/) is free, portable and easy to use.
- Open `dx11\rl_x64_f.dll` in hex editor. Use `Browse local files` in Steam game options to find path to Quantum Break folder.
- Search for `0FBAE117730A` hex string.
- Replace it with `0FBAE1179090` hex string.

![remove_popcnt_check](https://user-images.githubusercontent.com/7583050/42335737-0059a994-808a-11e8-90e8-57c040eaac70.gif)

More info: https://twitter.com/beatcracker/status/1014261058335371275

**Comment by lolroflmywaffle** [comment]
Back after a long stretch of computer problems.  I'm so glad you decided to post your fix here.  Can confirm that it does work, though the game would fail to launch due to "renderer_x64_f.dll" acting up.

I updated Quantum Break and used a separate cracked 'launcher' and success, upon launch I get a "The program can't start because api-ms-win-core-libraryloader-l1-2-0.dll is missing from your computer.  Try reinstalling the program to fix this problem." message, but clicking OK will launch the game anyways.

Before your fix using SDE emulator = 10-15 fps

Using your fix + patches = 60 fps (2560x1600 - normal/high settings)

Intel x5470 (Quadcore 4.25ghz, no Hyper-Threading)
8gb Ram @ 1700mhz
1070ti

Thanks to both of you guys for making this possible thru your posts, I hope others with old CPU's will find this thread somehow.  Or someone can make a YouTube video and garner some viewers...

**Comment by xflyboy** [comment]
> Just found your repo, awesome job!
> 
> I've been trying to fix this issue myself and found that `NOP`ing POPCNT check in `rl_x64_f.dll` works. It really looks like the codepaths with POPCNT are not used at all.
> 
> Here is [my solution](https://pcgamingwiki.com/wiki/Quantum_Break#POPCNT_instruction) if anybody interested:
> 
> * Get hex editor. [HxD](https://mh-nexus.de/en/hxd/) is free, portable and easy to use.
> * Open `dx11\rl_x64_f.dll` in hex editor. Use `Browse local files` in Steam game options to find path to Quantum Break folder.
> * Search for `0FBAE117730A` hex string.
> * Replace it with `0FBAE1179090` hex string.
> 
> ![remove_popcnt_check](https://user-images.githubusercontent.com/7583050/42335737-0059a994-808a-11e8-90e8-57c040eaac70.gif)
> 
> More info: https://twitter.com/beatcracker/status/1014261058335371275

Thanks. Worked like a charm.

**Comment by Himmler** [comment]
Great fix. Works perfect with Steam on E5450.

**Comment by AyushKumar-Codes** [comment]
Can you please fix this Problem in Marvel Avengers too.. As this pocnt missing error also occur in this game.. Please help me.
